title: Rahul Prabhu's Personal Website
name: Rahul Prabhu
description: Team AcYut | BITS Pilani CS
url: "https://favre49.github.io"
github: [metadata]
minimal_mistakes_skin: "default"
repository: "favre49/favre49.github.io"
include : [_pages]

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-feed