title: Rahul Prabhu
description: Team AcYut | BITS Pilani CS
baseurl: ""
url: "https://favre49.github.io"
github_username: favre49
github: [metadata]

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
  - jekyll-feed